version: '3'
services:
  api:
    image: "api:${TAG}"
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./api/.env
  pipeline:
    image: "pipeline:${TAG}"
    build: 
      context: ./pipeline
      dockerfile: Dockerfile
      args:
        - NPM_PASS=$NPM_PASS
        - NPM_USER=$NPM_USER
        - NPM_SCOPE=$NPM_SCOPE
        - NPM_EMAIL=$NPM_EMAIL
      ssh: 
        - default
    env_file:
      - ./pipeline/.env
    

