version: 1
default_environment: dev
project_id: c48d5eca-4f6c-45ab-af89-a7a7f875379a
send_anonymous_usage_stats: false
plugins:
  extractors:
    # - name: tap-ccxt
    #   namespace: tap_ccxt
    #   pip_url: git+ssh://git@github.com/superkeyio/tap-ccxt.git
    #   capabilities:
    #     - state
    #     - catalog
    #     - discover
    #   settings:
    #     - name: start_date
    #     - name: exchanges
    #   config:
    #     exchanges:
    #       - id: binance
    #         symbols:
    #           - symbol: TRIBE/USDT
    #             timeframe: 1m
    #           - symbol: ETH/USDT
    #             timeframe: 1m
    #           - symbol: BTC/USDT
    #             timeframe: 1m
    #       - id: ftx
    #         symbols:
    #           - symbol: LOOKS/USD
    #             timeframe: 1m
    #       - id: gateio
    #         symbols:
    #           - symbol: FEI_USDT
    #             timeframe: 1m
    #           - symbol: RAI_USDT
    #             timeframe: 1m
    #     start_date: "2022-04-01T00:00:00Z"
    - name: tap-ethereum # TODO: add config values for tap-ethereum
      namespace: tap_ethereum
      pip_url: git+ssh://git@github.com/superkeyio/tap-ethereum.git
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: ethereum_rpc
        - name: contracts
        - name: etherscan_api_key
        - name: confirmations
        - name: batch_size
        - name: concurrency
      config:
        concurrency: 50
        batch_size: 100
        confirmations: 12
        contracts:
          - name: AloeBlend
            abi: ./abi/aloe_blend.json
            instances:
              - name: USDC/WETH 0.05% cUSDC cETH
                address: "0x33cB657E7fd57F1f2d5f392FB78D5FA80806d1B4"
                start_block: 14170520
              - name: FEI/TRIBE 0.05% fFEI 8 fTRIBE 8
                address: "0x0B76ABb170519C292da41404fDc30Bb5BEf308Fc"
                start_block: 14164593
              - name: WBTC/WETH 0.05% yvWBTC yvWETH
                address: "0xE801c4175A0341e65dFef8F3B79e1889047AfEbb"
                start_block: 14164820
              - name: RAI/WETH 0.30% fRAI 9 yvWETH
                address: "0x37dc6FCb5C03d46b097B094785c9fA557aa32fd4"
                start_block: 14261737
              - name: WETH/LOOKS 0.30% cETH LooksRare Staking
                address: "0x021016FbB4d3AAeaA440508C5E06Ce8c1039FCCD"
                start_block: 14279169
            events:
              - Transfer
            getters:
              - getInventory
              - totalSupply
          - name: G-UNI
            abi: ./abi/g_uni.json
            instances:
              - name: USDC/WETH 0.05%
                address: "0xa6c49FD13E50a30C65E6C8480aADA132011D0613"
                start_block: 14170520 # Start when Aloe Blend USDC/WETH vault was created
            getters:
              - getUnderlyingBalances
              - totalSupply
          - name: Visor
            abi: ./abi/visor.json
            instances:
              - name: USDC/WETH
                address: "0x716bd8A7f8A44B010969A1825ae5658e7a18630D"
                start_block: 14170520 # Start when Aloe Blend USDC/WETH vault was created
            getters:
              - getTotalAmounts
              - totalSupply
          - name: Charm
            abi: ./abi/charm.json
            instances:
              - name: USDC/WETH
                address: "0x9bF7B46C7aD5ab62034e9349Ab912C0345164322"
                start_block: 14170520 # Start when Aloe Blend USDC/WETH vault was created
            getters:
              - getTotalAmounts
              - totalSupply
          - name: Uni V2
            abi: ./abi/uni_v2.json
            instances:
              - name: USDC/WETH
                address: "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc"
                start_block: 14170520 # Start when Aloe Blend USDC/WETH vault was created
            getters:
              - getReserves
              - totalSupply
          - name: Popsicle
            abi: ./abi/popsicle.json
            instances:
              - name: USDC/WETH
                address: "0xaE7b92C8B14E7bdB523408aE0A6fFbf3f589adD9"
                start_block: 14170520 # Start when Aloe Blend USDC/WETH vault was created
            getters:
              - usersAmounts
              - totalSupply
    - name: tap-thegraph # TODO: add config values for tap-ethereum
      namespace: tap_thegraph
      pip_url: git+ssh://git@github.com/superkeyio/tap-thegraph.git
      capabilities:
        - state
        - catalog
        - discover
  loaders:
    - name: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres
      config:
        add_metadata_columns: true
        flush_all_streams: true
        batch_size_rows: 100
  # orchestrators:
  #   - name: airflow
  #     pip_url: psycopg2 apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  # files:
  #   - name: airflow
  #     pip_url: git+https://gitlab.com/meltano/files-airflow.git
# schedules:
#   - name: ccxt-to-postgres
#     extractor: tap-ccxt
#     loader: target-postgres
#     transform: skip
#     interval: "* * * * *"
#     start_date: 2022-04-01 00:00:00
environments:
  - name: dev
  - name: staging
  - name: prod
