version: 1
default_environment: dev
project_id: c48d5eca-4f6c-45ab-af89-a7a7f875379a
send_anonymous_usage_stats: false
plugins:
  extractors:
  - name: tap-ccxt
    namespace: tap_ccxt
    pip_url: git+ssh://git@github.com/superkeyio/tap-ccxt.git@1b2c59b5c8fb9ef63c6275ca647ea3d52be690e2
    capabilities:
    - state
    - catalog
    - discover
    config:
      exchanges:
      - id: binance
        pairs:
        - base: ETH
          quote: USDT
          timeframe: 1m
          start_date: '2022-05-25T00:00:00Z'
      - id: kraken
        pairs:
        - base: USDC
          quote: USD
          timeframe: 1m
          start_date: '2022-05-25T00:00:00Z'
  - name: tap-ethereum
    namespace: tap_ethereum
    pip_url: git+ssh://git@github.com/superkeyio/tap-ethereum.git@7b2bab5bad84cb96be4beed0f920fdfdc2be1f78
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: ethereum_rpc
    - name: contracts
    - name: etherscan_api_key
    - name: confirmations
    - name: batch_size
    - name: concurrency
    config:
      concurrency: 50
      batch_size: 100
      confirmations: 12
      contracts:
      - name: AloeBlend
        abi: ./abi/aloe_blend.json
        instances:
        - name: USDC/WETH 0.05% cUSDC cETH
          address: '0x33cB657E7fd57F1f2d5f392FB78D5FA80806d1B4'
          start_block: 14164514
        events:
        - Transfer
  - name: tap-thegraph
    namespace: tap_thegraph
    pip_url: git+ssh://git@github.com/superkeyio/tap-thegraph.git@91923fbf60d305afa6ff849b88798b72961a5a70
    capabilities:
    - state
    - catalog
    - discover
    config:
      subgraphs:
      - url: https://api.thegraph.com/subgraphs/name/stakewise/ethereum-mainnet
        entities:
        - name: Block
          created_at: id
          since: '14164514'
      batch_size: 1000
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      add_metadata_columns: true
      flush_all_streams: true
      batch_size_rows: 1000
  transformers:
  - name: dbt-postgres
    pip_url: dbt-core~=1.0.0 dbt-postgres~=1.0.0
environments:
- name: dev
  config:
    plugins:
      transformers:
      - name: dbt-postgres
- name: staging
- name: prod
