version: '3'
services:
  api:
    image: "${GCR_PATH}/api:latest"
    env_file:
      - ./api/.env.prod
  pipeline:
    image: "${GCR_PATH}/pipeline:latest"
    env_file:
      - ./pipeline/.env.prod
    

